export interface DataProperties {
    id: number,
    titulo: string,
    slug: string,
    ubicacion: string,
    precio: number,
    habitaciones: number,
    baños: number,
    puntuacion: number,
    metros: number,
    categoria: string,
    descripcion: string,
    telefono: string
    images: string[]
}

export const dataProperties: DataProperties[] = [
    {
        id: 1,
        titulo: "Elegante Piso en el Centro de Madrid con Balcón y Vistas",
        slug: "elegante-piso-en-el-centro-de-madrid-con-balcon-y-vistas",
        ubicacion: "Madrid",
        precio: 380000,
        habitaciones: 4,
        baños: 3,
        puntuacion: 4.7,
        metros: 180,
        categoria: "mansiones",
        descripcion: "Este espectacular piso en el centro de Madrid ofrece una experiencia de lujo con sus acabados modernos y su estratégica ubicación...",
        telefono: "600123456",
        images: ['/assets/properties/propertie1.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg'],
    },
    {
        id: 2,
        titulo: "Ático de Lujo con Terraza y Vistas al Mar en Barcelona",
        slug: "atico-de-lujo-con-terraza-y-vistas-al-mar-en-barcelona",
        ubicacion: "Barcelona",
        precio: 395000,
        habitaciones: 5,
        baños: 3,
        puntuacion: 4.9,
        metros: 220,
        categoria: "tropical",
        descripcion: "Este exclusivo ático se encuentra en una de las mejores zonas de Barcelona, ofreciendo una combinación única de comodidad y vistas impresionantes...",
        telefono: "601234567",
        images: ['/assets/properties/propertie2.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 3,
        titulo: "Encantadora Casa con Jardín y Terraza en Valencia",
        slug: "encantadora-casa-con-jardin-y-terraza-en-valencia",
        ubicacion: "Valencia",
        precio: 270000,
        habitaciones: 3,
        baños: 2,
        puntuacion: 4.5,
        metros: 190,
        categoria: "campo",
        descripcion: "Ubicada en una tranquila zona residencial a pocos minutos de la playa, esta hermosa casa independiente es ideal para quienes buscan paz y comodidad...",
        telefono: "602345678",
        images: ['/assets/properties/propertie3.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 4,
        titulo: "Casa Tradicional Sevillana Reformada en el Centro Histórico",
        slug: "casa-tradicional-sevillana-reformada-en-el-centro-historico",
        ubicacion: "Sevilla",
        precio: 180000,
        habitaciones: 3,
        baños: 2,
        puntuacion: 4.2,
        metros: 165,
        categoria: "campo",
        descripcion: "Situada en el corazón del casco histórico de Sevilla, esta casa tradicional ha sido completamente reformada sin perder su esencia andaluza...",
        telefono: "603456789",
        images: ['/assets/properties/propertie4.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 5,
        titulo: "Chalet Exclusivo con Piscina y Vistas al Mar en Málaga",
        slug: "chalet-exclusivo-con-piscina-y-vistas-al-mar-en-malaga",
        ubicacion: "Málaga",
        precio: 400000,
        habitaciones: 6,
        baños: 4,
        puntuacion: 4.9,
        metros: 350,
        categoria: "mansiones",
        descripcion: "Este espectacular chalet se encuentra en una de las mejores zonas de Málaga, con vistas impresionantes al mar y una piscina privada rodeada de jardines tropicales...",
        telefono: "604567890",
        images: ['/assets/properties/propertie5.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 6,
        titulo: "Cabaña de Madera con Chimenea en Sierra Nevada",
        slug: "cabana-de-madera-con-chimenea-en-sierra-nevada",
        ubicacion: "Sierra Nevada",
        precio: 180000,
        habitaciones: 2,
        baños: 1,
        puntuacion: 4.5,
        metros: 150,
        categoria: "cabanas",
        descripcion: "Una acogedora cabaña de madera en plena naturaleza, perfecta para disfrutar del invierno rodeado de nieve y montañas...",
        telefono: "614567890",
        images: ['/assets/properties/propertie6.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 7,
        titulo: "Casa Adosada con Patio y Garaje en Urbanización Tranquila",
        slug: "casa-adosada-con-patio-y-garaje-en-urbanizacion-tranquila",
        ubicacion: "Alicante",
        precio: 230000,
        habitaciones: 4,
        baños: 2,
        puntuacion: 4.6,
        metros: 180,
        categoria: "campo",
        descripcion: "Ubicada en una de las mejores urbanizaciones de Alicante, esta casa adosada ofrece comodidad y privacidad...",
        telefono: "605678901",
        images: ['/assets/properties/propertie7.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 8,
        titulo: "Piso Moderno con Garaje y Terraza en Bilbao",
        slug: "piso-moderno-con-garaje-y-terraza-en-bilbao",
        ubicacion: "Bilbao",
        precio: 310000,
        habitaciones: 5,
        baños: 3,
        puntuacion: 4.8,
        metros: 250,
        categoria: "mansiones",
        descripcion: "Este impresionante piso de diseño moderno se encuentra en un edificio de reciente construcción con todas las comodidades...",
        telefono: "606789012",
        images: ['/assets/properties/propertie8.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 9,
        titulo: "Vivienda Unifamiliar con Patio Privado y Terraza en Zaragoza",
        slug: "vivienda-unifamiliar-con-patio-privado-y-terraza-en-zaragoza",
        ubicacion: "Zaragoza",
        precio: 190000,
        habitaciones: 3,
        baños: 2,
        puntuacion: 4.1,
        metros: 170,
        categoria: "campo",
        descripcion: "Ubicada en una zona tranquila de Zaragoza, esta vivienda unifamiliar ofrece un ambiente acogedor con un gran patio privado y terraza...",
        telefono: "607890123",
        images: ['/assets/properties/propertie9.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 10,
        titulo: "Casa Rústica con Jardín y Piscina Privada en Granada",
        slug: "casa-rustica-con-jardin-y-piscina-privada-en-granada",
        ubicacion: "Granada",
        precio: 250000,
        habitaciones: 4,
        baños: 3,
        puntuacion: 4.5,
        metros: 210,
        categoria: "campo",
        descripcion: "Hermosa casa de pueblo restaurada con materiales de alta calidad, manteniendo su esencia rústica...",
        telefono: "608901234",
        images: ['/assets/properties/propertie10.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 11,
        titulo: "Finca con Viñedos y Casa Rural en La Rioja",
        slug: "finca-con-vinedos-y-casa-rural-en-la-rioja",
        ubicacion: "La Rioja",
        precio: 320000,
        habitaciones: 4,
        baños: 3,
        puntuacion: 4.8,
        metros: 400,
        categoria: "campo",
        descripcion: "Hermosa finca con viñedos en plena producción. La casa rural tiene una construcción de piedra con detalles en madera, un salón con chimenea, cocina totalmente equipada y amplias habitaciones con vistas al viñedo...",
        telefono: "610123456",
        images: ['/assets/properties/propertie11.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 12,
        titulo: "Villa Moderna con Piscina en Tenerife",
        slug: "villa-moderna-con-piscina-en-tenerife",
        ubicacion: "Tenerife",
        precio: 370000,
        habitaciones: 5,
        baños: 4,
        puntuacion: 4.9,
        metros: 450,
        categoria: "tropical",
        descripcion: "Una villa moderna con un diseño vanguardista, piscina infinita y espectaculares vistas al océano. El interior cuenta con espacios abiertos, materiales de alta gama y domótica de última generación...",
        telefono: "611234567",
        images: ['/assets/properties/propertie12.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 13,
        titulo: "Casa de Playa con Piscina y Terraza en Cádiz",
        slug: "casa-de-playa-con-piscina-y-terraza-en-cadiz",
        ubicacion: "Cádiz",
        precio: 300000,
        habitaciones: 4,
        baños: 3,
        puntuacion: 4.8,
        metros: 250,
        categoria: "tropical",
        descripcion: "Fantástica casa de playa con acceso directo al mar, piscina privada y terrazas con vistas al océano. La casa cuenta con un diseño elegante, espacios amplios y un jardín tropical...",
        telefono: "618901234",
        images: ['/assets/properties/propertie13.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 14,
        titulo: "Casa Señorial con Jardín en Toledo",
        slug: "casa-señorial-con-jardin-en-toledo",
        ubicacion: "Toledo",
        precio: 350000,
        habitaciones: 6,
        baños: 4,
        puntuacion: 4.7,
        metros: 500,
        categoria: "mansiones",
        descripcion: "Magnífica casa señorial con un extenso jardín y detalles arquitectónicos históricos. La propiedad conserva su estructura original con toques de modernidad, ofreciendo un ambiente elegante y exclusivo...",
        telefono: "615678901",
        images: ['/assets/properties/propertie14.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 15,
        titulo: "Chalet de Lujo con Vistas a la Montaña en Andorra",
        slug: "chalet-de-lujo-con-vistas-a-la-montaña-en-andorra",
        ubicacion: "Andorra",
        precio: 395000,
        habitaciones: 4,
        baños: 3,
        puntuacion: 4.9,
        metros: 420,
        categoria: "mansiones",
        descripcion: "Chalet de lujo con amplias estancias, terrazas soleadas y vistas impresionantes a los Pirineos. Ideal para los amantes del esquí y la montaña...",
        telefono: "616789012",
        images: ['/assets/properties/propertie15.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 16,
        titulo: "Cabaña Acogedora con Bosque Privado en Asturias",
        slug: "cabana-acogedora-con-bosque-privado-en-asturias",
        ubicacion: "Asturias",
        precio: 250000,
        habitaciones: 3,
        baños: 2,
        puntuacion: 4.6,
        metros: 180,
        categoria: "cabanas",
        descripcion: "Rodeada de naturaleza, esta cabaña rústica ofrece una experiencia única para los amantes de la tranquilidad. Su amplio salón con chimenea y vistas al bosque crea un ambiente cálido y acogedor...",
        telefono: "617890123",
        images: ['/assets/properties/propertie16.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 17,
        titulo: "Casa Rural con Encanto en los Picos de Europa",
        slug: "casa-rural-con-encanto-en-los-picos-de-europa",
        ubicacion: "Cantabria",
        precio: 280000,
        habitaciones: 5,
        baños: 3,
        puntuacion: 4.7,
        metros: 210,
        categoria: "campo",
        descripcion: "Una preciosa casa rural rodeada de montañas y senderos naturales. Cuenta con un patio de piedra, cocina rústica con horno de leña y habitaciones luminosas con vistas panorámicas...",
        telefono: "618901345",
        images: ['/assets/properties/propertie4.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 18,
        titulo: "Lujosa Villa en Ibiza con Acceso Privado a la Playa",
        slug: "lujosa-villa-en-ibiza-con-acceso-privado-a-la-playa",
        ubicacion: "Ibiza",
        precio: 400000,
        habitaciones: 6,
        baños: 5,
        puntuacion: 5.0,
        metros: 600,
        categoria: "tropical",
        descripcion: "Una villa de ensueño en Ibiza con un diseño moderno y acceso directo a la playa. Cuenta con amplias terrazas, piscina infinita y un interior con acabados de lujo...",
        telefono: "619012345",
        images: ['/assets/properties/propertie2.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 19,
        titulo: "Chalet con Vistas al Mar en San Sebastián",
        slug: "chalet-con-vistas-al-mar-en-san-sebastian",
        ubicacion: "San Sebastián",
        precio: 390000,
        habitaciones: 5,
        baños: 4,
        puntuacion: 4.9,
        metros: 500,
        categoria: "mansiones",
        descripcion: "Un chalet espectacular en lo alto de una colina con vistas panorámicas al mar. La propiedad cuenta con un gran jardín, piscina y amplios ventanales para disfrutar del paisaje...",
        telefono: "620123456",
        images: ['/assets/properties/propertie14.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    },
    {
        id: 20,
        titulo: "Casa de Montaña con Vistas Espectaculares en La Alpujarra",
        slug: "casa-de-montaña-con-vistas-espectaculares-en-la-alpujarra",
        ubicacion: "Granada",
        precio: 260000,
        habitaciones: 3,
        baños: 2,
        puntuacion: 4.5,
        metros: 200,
        categoria: "campo",
        descripcion: "Esta encantadora casa de montaña ofrece un refugio perfecto con impresionantes vistas de La Alpujarra. Dispone de un salón con chimenea, terraza y un entorno rodeado de naturaleza...",
        telefono: "621234567",
        images: ['/assets/properties/propertie9.jpeg', '/assets/properties/propertie2.jpeg', '/assets/properties/propertie3.jpeg']
    }
]