export const dataProperties = [
  {
    id: 1,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie1.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.5,
    meters: 430,
    phone: "923456781",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 2,
    location: "Cuenca, Valencia, ES",
    price: 150000,
    bedrooms: 2,
    bathroom: 2,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4,
    meters: 230,
    phone: "923456782",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 3,
    location: "Cuenca, Valencia, ES",
    price: 35.0,
    bedrooms: 5,
    bathroom: 2,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 5,
    meters: 90,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 4,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.2,
    meters: 120,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 5,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.1,
    meters: 87,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 6,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 3.7,
    meters: 220,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 7,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.5,
    meters: 430,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 8,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.5,
    meters: 330,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 9,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.5,
    meters: 380,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 10,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.1,
    meters: 270,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 11,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 5,
    meters: 430,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 12,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 3.9,
    meters: 76,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 13,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.8,
    meters: 290,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 14,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.9,
    meters: 180,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 15,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4.1,
    meters: 287,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 16,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    images: ["/assets/properties/propertie2.jpeg", "/assets/properties/propertie2.jpeg", "/assets/properties/propertie3.jpeg"],
    star: 4,
    meters: 290,
    phone: "923456789",
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
];
